### ISSUE TITLE
Add your names to the collaborators.txt file

### ISSUE THREAD

**Issue by Riyu44** [Riyu44/testmavenCICD#3]
Please add your own name to the txt file and follow the readme practices.

**Comment by Riyu44** [comment]
Added my name to the file.

**Comment by Tushar-2510** [comment]
I have added my name

**Comment by XpectoPatronum** [comment]
Added my name to the file

**Comment by Riyu44** [comment]
@navvay please complete this to close the issue

**Comment by navvay** [comment]
Added my name
